name: test_workflow
on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Checks out the repository code

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Sets up a specific Node.js version
        with:
          node-version: "20" # Specify the desired Node.js version (e.g., 20)

      - name: Install dependencies
        run: npm install
        # Optionally specify working-directory if package.json is not in root:
        # working-directory: ./path/to/project

      - name: Finishing up
        run: echo "Done!"
